displayName=All-in-One Reminders
author=Ratbag24
description=Reminds you when your saturated heart, thrall, vengeance or divine potion needs re-applying
tags=heart,saturated,imbued,thrall,vengeance,divine,boost,reminder,timer,cooldown,buff
version=
plugins=com.ratbag24.reminders.RemindersPlugin
build=standard
