displayName=All-in-One Reminders
author=Ratbag24
description=Reminds you when your saturated heart is off cooldown, with a toggle per reminder
tags=heart,saturated,imbued,magic,boost,reminder,timer,cooldown
version=
plugins=com.ratbag24.reminders.RemindersPlugin
build=standard
